name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://amreshbofficial.github.io/</loc>' >> sitemap.xml
          echo '    <lastmod>$(date -I)</lastmod>' >> sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> sitemap.xml
          echo '    <priority>1.0</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap
        run: |
          git config --global user.name "Amreshbofficial"
          git config --global user.email "amreshbaskar@gmail.com"
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push origin main